version: '3'

services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf
      - ./gateway/mockBE.conf:/etc/nginx/mockBE.conf
    ports:
      - 9999:9999
